# Generated by Django 2.2 on 2021-06-28 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stepapp', '0005_auto_20210625_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsearch',
            name='userInfo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
